services:
  db:
    image: mysql:8.0
    container_name: cbgames-mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'devtest123'
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

volumes:
  db_data: